### ISSUE TITLE
404 after installation, php7

### ISSUE THREAD

**Issue by rickchew** [daylightstudio/FUEL-CMS-Campaign-Monitor-Module#3]
any idea ?

**Comment by daylightstudio** [comment]
Can you provide more information (e.g. what URL, screenshots, description of setup, etc)?

**Comment by daylightstudio** [comment]
There were a couple updates that have been pushed for the casing of the file name controller/Dashboard.php (as of CI 3, those files needed to be upper cased) and the CMBase.php script (from https://github.com/99designs/campaignmonitor-php/blob/master/CMBase.php) to work in PHP 7. This module is pretty old.

**Comment by rickchew** [comment]
alright, the problem solved
